---
name: snyk_merge

on: push

jobs:
 snyk_scan:
   runs-on: ubuntu-latest
   steps:
    - name: checkout the current PR
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        persist-credentials: false
    - name: Run Clojure Snyk Scan
      id: scan
      uses: puppetlabs/security-snyk-clojure-action@v1
      with:
        snykToken: ${{ secrets.SNYK_FOSS_KEY }}
        rproxyKey: ${{ secrets.SEC_PUBLIC_RPROXY_KEY }}
        snykOrg: 'puppet-foss'
        snykProject: 'pcp-broker'
    - name: Check output
      if: steps.scan.outputs.vulns != ''
      run: echo "Vulnerabilities detected; ${{ steps.scan.outputs.vulns }}" && exit 1
